name: vd-designer

services:
  vd-designer-ui:
    image: ghcr.io/aidbox/viewdefinitions-ui:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - "8280:80"
    profiles:
      - dev

  database:
    container_name: postgres-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - vdd-data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT}:5432"
    profiles:
      - dev
      - local

  test-db:
    container_name: test-db
    build:
      context: .
      dockerfile: ./docker/test_db.dockerfile
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    # NOTE: this ports are exposed because each time we create a temp db a new
    #   port should be used; this way we provide a range to secure our tests
    # ! IMPORTANT: this range specified in docker/test-db/getsocket.c as well
    ports:
      - "14500-15000:14500-15000"
    profiles:
      - local
      - tests

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command: --schedule "0 */5 * * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - dev

volumes:
  vdd-data:
    external: true
