apiVersion: v1
kind: PersistentVolume

metadata:
  name: vd-designer-database-volume
  namespace: viewdefinition

spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/postgresql
