apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: vd-designer-database-volume-claim
  namespace: viewdefinition

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
