apiVersion: apps/v1
kind: Deployment
metadata:
  name: vd-designer
  namespace: viewdefinition
spec:
  replicas: 2
  selector:
    matchLabels:
      service: vd-designer
  template:
    metadata:
      labels:
        service: vd-designer
    spec:
      containers:
        - name: vd-designer-client
          image: ghcr.io/aidbox/viewdefinitions-client:latest
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: viewdefinition
