apiVersion: v1
kind: Service

metadata:
  name: vd-designer-app
  namespace: viewdefinition

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    service: vd-designer
