(ns vd-designer.config
  (:require [clojure.edn :as edn]
            [taoensso.telemere :as t]
            [vd-designer.service.jwt :as jwt]
            [vd-designer.utils.base64 :as base64]))

(defn set-min-log-level!
  "Sets minimum level of Telemere signals (logs) generated by vd-designer.
   Possible levels (from most to least verbose):
    #{:trace :debug :info :warn :error :fatal :report}.

  The default level is `:info`"
  [level]
  (t/set-min-level! nil "vd-designer"   level)
  (t/set-min-level! nil "vd-designer.*" level)
  nil)

(def config
  {:log-level ;; #{:trace :debug :info :warn :error :fatal :report}
   :info

   :vd.designer.app/url
   (or (System/getenv "APP_HOST")
       "http://localhost:8080")

   :aidbox.portal/url
   (or (System/getenv "AIDBOX_PORTAL_URL")
       "http://127.0.0.1.nip.io:8789")

   :jwt
   {:jwk        (if-let [jwk (System/getenv "VD_AUTH_JWK")]
                  (-> jwk (base64/decode) edn/read-string)
                  (jwt/generate-jwk))
    :expires-in (* 60 #_SECONDS
                   60 #_MINUTES
                   24 #_HOURS)
    :sign-opts  {:alg :rs512}}

   :sso
   {:client-id            (or (System/getenv "AIDBOX_CLIENT_NAME")
                              "vd-designer")
    :client-secret        (or (System/getenv "AIDBOX_CLIENT_SECRET")
                              "changeme")
    :default-redirect-url (or (System/getenv "APP_HOST")
                              "http://localhost:8080")
    :provider-url         (or (System/getenv "AIDBOX_PORTAL_SSO_URL")
                              "http://127.0.0.1.nip.io:8789/ui/portal")}

   :db
   {:dbtype   "postgresql"
    :dbname   (or (System/getenv "POSTGRES_DB")
                  "vd-dev")
    :host     (or (System/getenv "POSTGRES_HOST")
                  "localhost")
    :port     (or (System/getenv "POSTGRES_PORT")
                  5454)
    :user     (or (System/getenv "POSTGRES_USER")
                  "vd-dev")
    :password (or (System/getenv "POSTGRES_PASSWORD")
                  "vd-dev")}

   :public-fhir-servers
   [{:server-name "Aidbox Sandbox"
     :box-url     "https://viewdefs.aidbox.app"
     :headers     {"Authorization" "Basic YmFzaWM6dmlld2RlZmluaXRpb25z"}}]})

(defonce ^:private __set-default-log-level (set-min-log-level! (:log-level config)))
