name: Client test

on:
  push:
    branches:
      - "**"
    paths:
      - "src/cljs/**"
      - "test/cljs/**"
      - "resources/client/**"
      - "test-resources/client/**"
      - "package.json"
      - "**.edn"
      - "**.js"

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.3.1463

      - name: Cache clj deps
        id: cache-clj-deps
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: clojure-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clojure-${{ hashFiles('**/deps.edn') }}-
            clojure-

      - name: Install rlwrap
        run: sudo apt -y update && sudo apt install -y rlwrap

      - name: Configure git to use another url to fetch npm packages from github and install deps
        run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"
        run: npm ci

      - name: Compile project
        run: clj -M:client:client-build

      - name: Compile tests
        run: clj -M:client:client-test:client-build-tests

      - name: Run tests
        run: node out/node-tests.js
