name: Clojure Dependency Checking

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}

    - name: Check Clojure Dependencies
      uses: nnichols/clojure-dependency-update-action@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
