name: Check dependencies
on:
  push:
    tags-ignore:
      - "**"
  # additionally run once per week (At 00:00 on Sunday) to maintain cache
  schedule:
    - cron: "0 0 * * 0"

jobs:
  antq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liquidz/antq-action@main
